### ISSUE TITLE
Bug: format-servers -private-internet-access doesn't work

### ISSUE THREAD

**Issue by parkr** [qdm12/gluetun#1987]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version v3.36.0 built on 2023-10-31T13:10:39.622Z (commit 1c43a1d)

### What's the problem 🤔

`format-servers -private-internet-access` doesn't work:

```console
/ # /gluetun-entrypoint format-servers -private-internet-access
panic: provider private-internet-access not found in hardcoded servers map; did you add the provider key in the embedded servers.json?

goroutine 35 [running]:
github.com/qdm12/gluetun/internal/storage.(*Storage).getMergedServersObject(0x7f541cc98f20?, {0xc000029080, 0x17})
	github.com/qdm12/gluetun/internal/storage/servers.go:115 +0x128
github.com/qdm12/gluetun/internal/storage.(*Storage).FormatToMarkdown(0x1089b80?, {0xc000029080, 0x17})
	github.com/qdm12/gluetun/internal/storage/servers.go:82 +0xe6
github.com/qdm12/gluetun/internal/cli.(*CLI).FormatServers(0x4?, {0xc000022140, 0x1, 0x1})
	github.com/qdm12/gluetun/internal/cli/formatservers.go:84 +0x745
main._main({0x108de80, 0xc0001c2320}, {{0x1087350, 0x7}, {0x1087358, 0x7}, {0x1088ad0, 0x18}}, {0xc000022120, 0x3, ...}, ...)
	./main.go:156 +0x49a
main.main.func1()
	./main.go:92 +0x12c
created by main.main in goroutine 1
	./main.go:91 +0x5e5
```

It appears the automagic conversion of spaces and hyphens in [`internal/cli/formatservers.go`](https://github.com/qdm12/gluetun/blob/master/internal/cli/formatservers.go) doesn't work for this provider.

The appropriate key from `/gluetun/servers.json` is `"private internet access"`. Perhaps it's trying to read `"private-internet-access"` by accident?

### Share your logs (at least 10 lines)

```plain text
/ # /gluetun-entrypoint format-servers -private-internet-access
panic: provider private-internet-access not found in hardcoded servers map; did you add the provider key in the embedded servers.json?

goroutine 35 [running]:
github.com/qdm12/gluetun/internal/storage.(*Storage).getMergedServersObject(0x7f541cc98f20?, {0xc000029080, 0x17})
	github.com/qdm12/gluetun/internal/storage/servers.go:115 +0x128
github.com/qdm12/gluetun/internal/storage.(*Storage).FormatToMarkdown(0x1089b80?, {0xc000029080, 0x17})
	github.com/qdm12/gluetun/internal/storage/servers.go:82 +0xe6
github.com/qdm12/gluetun/internal/cli.(*CLI).FormatServers(0x4?, {0xc000022140, 0x1, 0x1})
	github.com/qdm12/gluetun/internal/cli/formatservers.go:84 +0x745
main._main({0x108de80, 0xc0001c2320}, {{0x1087350, 0x7}, {0x1087358, 0x7}, {0x1088ad0, 0x18}}, {0xc000022120, 0x3, ...}, ...)
	./main.go:156 +0x49a
main.main.func1()
	./main.go:92 +0x12c
created by main.main in goroutine 1
	./main.go:91 +0x5e5
```

**Comment by qdm12** [comment]
Try pulling the latest image again? This got fixed last week (probably right at the same time you opened this issue) with commit 3e825d7a086f4113279cb89ae34e3e985a527bc4

Thanks for reporting it anyway 👍 !

**Comment by qdm12** [comment]
Closing due to inactivity
