### ISSUE TITLE
Bug:  newest update keeps crashing :(

### ISSUE THREAD

**Issue by theDiverDK** [qdm12/gluetun#2165]
### Is this urgent?

Yes

### Host OS

Unraid newest version

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2024-03-18T17:49:37.003Z (commit 3d16798)

### What's the problem 🤔

After upgrading today, GluetunVPN keeps crashing and restarting again and again :(

It worked perfectly before the upgrade

### Share your logs (at least 10 lines)

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2024-03-18T17:49:37.003Z (commit 3d16798)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-03-18T21:55:45+01:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
2024-03-18T21:55:45+01:00 INFO [routing] local ethernet link found: eth0
2024-03-18T21:55:45+01:00 INFO [routing] local ipnet found: 172.17.0.0/16
2024-03-18T21:55:45+01:00 INFO [firewall] enabling...
2024-03-18T21:55:45+01:00 INFO [firewall] enabled successfully
2024-03-18T21:55:46+01:00 INFO [storage] merging by most recent 17820 hardcoded servers and 17820 servers read from /gluetun/servers.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x760835]
goroutine 18 [running]:
github.com/qdm12/gluetun/internal/configuration/settings.(*ServerSelection).validate(0xc0002b6330, {0xc00002a035, 0x7}, {0x1098740?, 0xc0032fe000?})
	github.com/qdm12/gluetun/internal/configuration/settings/serverselection.go:149 +0xa55
github.com/qdm12/gluetun/internal/configuration/settings.(*Provider).validate(0xc0002b6328, {0xc000028081?, 0x9?}, {0x1098740, 0xc0032fe000})
	github.com/qdm12/gluetun/internal/configuration/settings/provider.go:47 +0x2fc
github.com/qdm12/gluetun/internal/configuration/settings.(*VPN).Validate(0xc0002b6318, {0x1098740, 0xc0032fe000}, 0xf0?)
	github.com/qdm12/gluetun/internal/configuration/settings/vpn.go:30 +0x165
github.com/qdm12/gluetun/internal/configuration/settings.(*Settings).Validate.func1()
	github.com/qdm12/gluetun/internal/configuration/settings/settings.go:52 +0x2b
github.com/qdm12/gluetun/internal/configuration/settings.(*Settings).Validate(0xc0002b6000, {0x1098740?, 0xc0032fe000}, 0x0)
	github.com/qdm12/gluetun/internal/configuration/settings/settings.go:57 +0x9cd
main._main({0x109d840, 0xc000288000}, {{0x1096954, 0x6}, {0x1096cd8, 0x7}, {0x1098470, 0x18}}, {0xc0000220a0, 0x1, ...}, ...)
	./main.go:240 +0xf9d
main.main.func1()
	./main.go:92 +0x12c
created by main.main in goroutine 1
	./main.go:91 +0x5e5
```

### Share your configuration

```yml
Dont use docker-compose in unraid

But my container details as seen in Portainer are:

:8388	:8388
BLOCK_ADS	off
BLOCK_MALICIOUS	on
BLOCK_SURVEILLANCE	off
DNS_ADDRESS	
DNS_KEEP_NAMESERVER	off
DNS_UPDATE_PERIOD	24h
DOT	on
DOT_CACHING	on
DOT_IPV6	off
DOT_PRIVATE_ADDRESS	127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112
DOT_PROVIDERS	cloudflare
DOT_VALIDATION_LOGLEVEL	0
DOT_VERBOSITY	1
DOT_VERBOSITY_DETAILS	0
FIREWALL	on
FIREWALL_DEBUG	off
FIREWALL_INPUT_PORTS	
FIREWALL_OUTBOUND_SUBNETS	
FIREWALL_VPN_INPUT_PORTS	
FREE_ONLY	
HEALTH_SERVER_ADDRESS	127.0.0.1:9999
HEALTH_SUCCESS_WAIT_DURATION	5s
HEALTH_TARGET_ADDRESS	github.com:443
HEALTH_VPN_DURATION_ADDITION	5s
HEALTH_VPN_DURATION_INITIAL	6s
HOST_CONTAINERNAME	GluetunVPN
HOST_HOSTNAME	Tower
HOST_OS	Unraid
HTTP_CONTROL_SERVER_ADDRESS	:8000
HTTP_CONTROL_SERVER_LOG	on
HTTPPROXY	off
HTTPPROXY_LISTENING_ADDRESS	:8888
HTTPPROXY_LOG	off
HTTPPROXY_PASSWORD	
HTTPPROXY_PASSWORD_SECRETFILE	/run/secrets/httpproxy_password
HTTPPROXY_STEALTH	off
HTTPPROXY_USER	
HTTPPROXY_USER_SECRETFILE	/run/secrets/httpproxy_user
ISP	
LOG_LEVEL	info
MULTIHOP_ONLY	
OPENVPN_AUTH	
OPENVPN_CERT	
OPENVPN_CIPHERS	
OPENVPN_CLIENTCRT_SECRETFILE	/run/secrets/openvpn_clientcrt
OPENVPN_CLIENTKEY_SECRETFILE	/run/secrets/openvpn_clientkey
OPENVPN_CUSTOM_CONFIG	
OPENVPN_ENCRYPTED_KEY	
OPENVPN_ENCRYPTED_KEY_SECRETFILE	/run/secrets/openvpn_encrypted_key
OPENVPN_FLAGS	
OPENVPN_IPV6	off
OPENVPN_KEY	
OPENVPN_KEY_PASSPHRASE	
OPENVPN_KEY_PASSPHRASE_SECRETFILE	/run/secrets/openvpn_key_passphrase
OPENVPN_PASSWORD	REMOVED
OPENVPN_PASSWORD_SECRETFILE	/run/secrets/openvpn_password
OPENVPN_PROCESS_USER	no
OPENVPN_PROTOCOL	udp
OPENVPN_USER	REMOVED11
OPENVPN_USER_SECRETFILE	/run/secrets/openvpn_user
OPENVPN_VERBOSITY	1
OPENVPN_VERSION	2.5
OWNED_ONLY	no
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID	1000
PORT_FORWARD_ONLY	
PPROF_BLOCK_PROFILE_RATE	0
PPROF_ENABLED	no
PPROF_HTTP_SERVER_ADDRESS	:6060
PPROF_MUTEX_PROFILE_RATE	0
PREMIUM_ONLY	
PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET	
PUBLICIP_API	ipinfo
PUBLICIP_API_TOKEN	
PUBLICIP_FILE	/gluetun/ip
PUBLICIP_PERIOD	12h
PUID	1000
SERVER_CITIES	Copenhagen
SERVER_COUNTRIES	Denmark
SERVER_HOSTNAMES	
SERVER_NAMES	
SERVER_NUMBER	
SERVER_REGIONS	Europe
SHADOWSOCKS	off
SHADOWSOCKS_CIPHER	chacha20-ietf-poly1305
SHADOWSOCKS_LISTENING_ADDRESS	:8388
SHADOWSOCKS_LOG	off
SHADOWSOCKS_PASSWORD	
SHADOWSOCKS_PASSWORD_SECRETFILE	/run/secrets/shadowsocks_password
TZ	Europe/Copenhagen
UNBLOCK	
UPDATER_MIN_RATIO	0.8
UPDATER_PERIOD	0
UPDATER_VPN_SERVICE_PROVIDERS	
VERSION_INFORMATION	on
VPN_ENDPOINT_IP	
VPN_ENDPOINT_PORT	
VPN_INTERFACE	tun0
VPN_PORT_FORWARDING	off
VPN_PORT_FORWARDING_LISTENING_PORT	0
VPN_PORT_FORWARDING_PROVIDER	
VPN_PORT_FORWARDING_STATUS_FILE	/tmp/gluetun/forwarded_port
VPN_SERVICE_PROVIDER	nordvpn
VPN_TYPE	wireguard
WIREGUARD_ADDRESSES	
WIREGUARD_ALLOWED_IPS	
WIREGUARD_IMPLEMENTATION	auto
WIREGUARD_MTU	1400
WIREGUARD_PRESHARED_KEY	
WIREGUARD_PRIVATE_KEY	REMOVED
WIREGUARD_PUBLIC_KEY
```

**Comment by Chifilly** [comment]
Maybe the same or similar issue as #2163 

Try downgrading to use the `v3` tag instead of `latest`

**Comment by ryandyf** [comment]
Same issue as well! Downgrading to v3 like @Chifilly got me back up and running.

**Comment by ryanjohnignacio** [comment]
> Same issue as well! Downgrading to v3 like @Chifilly said got me back up and running.

newbie how did you downgrade i removed my existing docker container

**Comment by ryandyf** [comment]
Are you using docker compose? Just remove the latest tag and replace it with v3

**Comment by ryanjohnignacio** [comment]
> Are you using docker compose? Just remove the latest tag and replace it with v3

version: "v3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=

**Comment by ryandyf** [comment]
> > Are you using docker compose? Just remove the latest tag and replace it with v3
> 
> 
> 
> version: "v3"
> 
> services:
> 
>   gluetun:
> 
>     image: qmcgaw/gluetun
> 
>     cap_add:
> 
>       - NET_ADMIN
> 
>     environment:
> 
>       - VPN_SERVICE_PROVIDER=nordvpn
> 
>       - VPN_TYPE=openvpn
> 
>       - OPENVPN_USER=
> 
>       - OPENVPN_PASSWORD=
> 
>       - SERVER_COUNTRIES=

Ah I see the mistake. Remove the version line, you don't need it!
On the image line, change it to this:

>     image: qmcgaw/gluetun:v3

**Comment by ryanjohnignacio** [comment]
> > > Are you using docker compose? Just remove the latest tag and replace it with v3
> > 
> > 
> > version: "v3"
> > services:
> > gluetun:
> > ```
> > image: qmcgaw/gluetun
> > 
> > cap_add:
> > 
> >   - NET_ADMIN
> > 
> > environment:
> > 
> >   - VPN_SERVICE_PROVIDER=nordvpn
> > 
> >   - VPN_TYPE=openvpn
> > 
> >   - OPENVPN_USER=
> > 
> >   - OPENVPN_PASSWORD=
> > 
> >   - SERVER_COUNTRIES=
> > ```
> 
> Ah I see the mistake. Remove the version line, you don't need it! On the image line, change it to this:
> 
> > ```
> > image: qmcgaw/gluetun:v3
> > ```

THANK YOU SOO MUCH

**Comment by ryandyf** [comment]
No problem!!! I've been there, you'll get it one day :)

**Comment by armengpt** [comment]
Same issue here - thanks for the v3 tip!

**Comment by theDiverDK** [comment]
Thanks for the V3 tip.

I actually asked for v3.37.0 and that worked as well.
Found out that was the version before it started crashing,

Have a great day

**Comment by pCoder3000** [comment]
got similar issue

**Comment by treverehrfurth** [comment]
Just came here to say I also had the same issue. 
Watchtower updated and gluetun was broken.
Changed :latest to :v3 and i'm back like the others.

**Comment by qdm12** [comment]
Working on it, sorry for the delay

**Comment by Yeastdonkey** [comment]
Same issue, reverting to v3 as noted in #855 and here resolved.

**Comment by qdm12** [comment]
🏳️ sorry everybody, bad PR, bad PR review, notifications turned off, sorry for the tunnel-interruption! 🏳️ 

This is fixed with 62158a17399ddbae68ad2e90ec11c8cf12439c1f

**Comment by qdm12** [comment]
If it's not solved, feel free to comment here exceptionally, I'll check back the rest of the day, but it *should* work (it works on my end).

**Comment by Yeastdonkey** [comment]
We appreciate your work, thanks!

**Comment by cvsickle** [comment]
Fixed the issue for me. Thanks for the quick work.

**Comment by armengpt** [comment]
I am with Mr. Yeast Donkey - thank you for all your work on this project!  Confirming **latest** has resolved the issue.

**Comment by theDiverDK** [comment]
Thanks for fixing the bug so quickly :)
