### ISSUE TITLE
Bug: Container crashes when port forwarding is ON

### ISSUE THREAD

**Issue by lamarios** [qdm12/gluetun#448]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Arch

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: PIA

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs) 

```
2021-05-12T01:01:30Z (commit 0099c06)
```

**What's the problem** 🤔

When enabling port forward, the container crashes. It used to work until last night.

**Share your logs... (careful to remove in example tokens)**

container  set up
```
pia:
  image: qmcgaw/gluetun
  container_name: pia
  restart: always
  cap_add:
   - NET_ADMIN
  init: true
  devices:
   - /dev/net/tun
  ports:
   - "9091:9091" # tranpsmission web ui
   - "8989:8989" # sonarr web ui
   - "7878:7878" # radarr web ui
   - "9999:9999/tcp" # transmission seeding port
   - "9999:9999/udp" # transmission seeding port
   - "9117:9117" # jackett web ui
   - "14324:8000"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./pia/forwarded_port:/forwarded_port
  environment:
   VPNSP: "private internet access"
   OPENVPN_USER: myuser
   OPENVPN_PASSWORD: mypassword
   PROTOCOL: udp
   ENCRYPTION: strong
   PORT_FORWARDING: "on"
     #   PORT_FORWARDING_STATUS_FILE: "/forwarded_port"
   REGION: "Singapore"
   EXTRA_SUBNETS: 192.168.7.0/24
   SHADOWSOCKS: "off"
   SHADOWSOCKS_PASSWORD: ""
   TINYPROXY: "off"
   TINYPROXY_USER: ""
   TINYPROXY_PASSWORD: ""

```

Container logs:

```log
pia                     | 2021/05/12 04:27:18 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]138.199.24.10:1197
pia                     | 2021/05/12 04:27:18 INFO openvpn: UDP link local: (not bound)
pia                     | 2021/05/12 04:27:18 INFO openvpn: UDP link remote: [AF_INET]138.199.24.10:1197
pia                     | 2021/05/12 04:27:19 INFO openvpn: [singapore404] Peer Connection Initiated with [AF_INET]138.199.24.10:1197
pia                     | 2021/05/12 04:27:19 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
pia                     | 2021/05/12 04:27:20 INFO openvpn: sitnl_send: rtnl: generic error (-101): Network unreachable
pia                     | 2021/05/12 04:27:20 INFO openvpn: TUN/TAP device tun0 opened
pia                     | 2021/05/12 04:27:20 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
pia                     | 2021/05/12 04:27:20 INFO openvpn: /sbin/ip link set dev tun0 up
pia                     | 2021/05/12 04:27:20 INFO openvpn: /sbin/ip addr add dev tun0 10.9.110.3/24
pia                     | 2021/05/12 04:27:20 WARN openvpn: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
pia                     | 2021/05/12 04:27:20 INFO openvpn: add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
pia                     | 2021/05/12 04:27:20 ERROR openvpn: RTNETLINK answers: Permission denied
pia                     | 2021/05/12 04:27:20 INFO openvpn: ERROR: Linux route -6 add command failed: external program exited with error status: 2
pia                     | 2021/05/12 04:27:20 INFO openvpn: Initialization Sequence Completed
pia                     | 2021/05/12 04:27:20 INFO VPN routing IP address: 138.199.24.10
pia                     | 2021/05/12 04:27:20 INFO dns over tls: downloading DNS over TLS cryptographic files
pia                     | 2021/05/12 04:27:20 INFO healthcheck: healthy!
pia                     | 2021/05/12 04:27:23 INFO dns over tls: downloading hostnames and IP block lists
pia                     | 2021/05/12 04:27:24 INFO dns over tls: init module 0: validator
pia                     | 2021/05/12 04:27:24 INFO dns over tls: init module 1: iterator
pia                     | 2021/05/12 04:27:24 INFO dns over tls: start of service (unbound 1.13.0).
pia                     | 2021/05/12 04:27:24 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
pia                     | 2021/05/12 04:27:24 INFO dns over tls: ready
pia                     | 2021/05/12 04:27:24 INFO You are running on the bleeding edge of latest!
pia                     | 2021/05/12 04:27:24 INFO VPN gateway IP address: 10.9.110.1
pia                     | panic: assignment to entry in nil map
pia                     | 
pia                     | goroutine 41 [running]:
pia                     | net/url.Values.Add(...)
pia                     | 	net/url/url.go:904
pia                     | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.fetchPortForwardData(0xcb36b8, 0xc0000a20c0, 0xc000350a50, 0xc0001244e4, 0x4, 0x3c4, 0xc0012e0000, 0x7c, 0xc000960000, 0x0, ...)
pia                     | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:359 +0x16b
pia                     | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.refreshPIAPortForwardData(0xcb36b8, 0xc0000a20c0, 0xc0001f67b0, 0xc000350a50, 0xc0001244e4, 0x4, 0x3c4, 0xc0002da438, 0x0, 0xc0012e0000, ...)
pia                     | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:176 +0x1d0
pia                     | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*PIA).PortForward.func1(0xc000350a01, 0xc000961b50)
pia                     | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:69 +0xb6
pia                     | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.tryUntilSuccessful(0xcb36b8, 0xc0000a20c0, 0xcb43b8, 0xc000076870, 0xc000961e18)
pia                     | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/try.go:14 +0x55
pia                     | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*PIA).PortForward(0xc00025a000, 0xcb36b8, 0xc0000a20c0, 0xc0001f67b0, 0xc0002da438, 0xcb43b8, 0xc000076870, 0xc0001244e4, 0x4, 0x3c4, ...)
pia                     | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:68 +0x437
pia                     | github.com/qdm12/gluetun/internal/openvpn.(*looper).portForward(0xc00031e000, 0xcb36b8, 0xc0000a20c0, 0xcb2500, 0xc00025a000, 0xc0001f67b0, 0xc0001244e4, 0x4, 0x3c4)
pia                     | 	github.com/qdm12/gluetun/internal/openvpn/loop.go:306 +0x1a7
pia                     | github.com/qdm12/gluetun/internal/openvpn.(*looper).Run.func1(0xc0001fe480, 0xc00031e000, 0xcb2500, 0xc00025a000, 0xcb36b8, 0xc0000a20c0)
pia                     | 	github.com/qdm12/gluetun/internal/openvpn/loop.go:180 +0x1a5
pia                     | created by github.com/qdm12/gluetun/internal/openvpn.(*looper).Run
pia                     | 	github.com/qdm12/gluetun/internal/openvpn/loop.go:173 +0xab8

```

**Comment by jarulsamy** [comment]
I am running into the same issue. I can confirm this is only an issue on the new v3.17.0 version, running the same docker-compose file on v3.16.0 works properly.

For now, I am using the old version as a workaround:
```
image: qmcgaw/gluetun:v3.16.0
```

In case it is helpful, I will include my logs and compose file as well:
```
version: "3.3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9091:9091/tcp # Transmission
      - 9092:9092/tcp # qBittorrent
    volumes:
      - ./data-gluetun:/gluetun
    environment:
      - TZ=America/Denver
      - VPNSP=private internet access
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - REGION=${REGION}
      - PUBLICIP_FILE=/gluetun/ip
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
    restart: unless-stopped
```

```
Attaching to gluetun
gluetun         | =========================================
gluetun         | ================ Gluetun ================
gluetun         | =========================================
gluetun         | ==== A mix of OpenVPN, DNS over TLS, ====
gluetun         | ======= Shadowsocks and HTTP proxy ======
gluetun         | ========= all glued up with Go ==========
gluetun         | =========================================
gluetun         | =========== For tunneling to ============
gluetun         | ======== your favorite VPN server =======
gluetun         | =========================================
gluetun         | === Made with ❤️  by github.com/qdm12 ====
gluetun         | =========================================
gluetun         | 
gluetun         | Running version latest built on 2021-05-11T17:16:13Z (commit e8c8742)
gluetun         | 
gluetun         | 
gluetun         | 🔧  Need help? https://github.com/qdm12/gluetun/issues/new
gluetun         | 💻  Email? quentin.mcgaw@gmail.com
gluetun         | ☕  Slack? Join from the Slack button on Github
gluetun         | 💸  Help me? https://github.com/sponsors/qdm12
gluetun         | 2021/05/11 20:12:46 INFO IPtables version: v1.8.6
gluetun         | 2021/05/11 20:12:46 INFO OpenVPN version: 2.5.2
gluetun         | 2021/05/11 20:12:46 INFO Unbound version: 1.13.0
gluetun         | 2021/05/11 20:12:46 INFO Settings summary below:
gluetun         | |--OpenVPN:
gluetun         |    |--Verbosity level: 1
gluetun         |    |--Run as root: enabled
gluetun         |    |--Provider:
gluetun         |       |--Private Internet Access settings:
gluetun         |          |--Network protocol: udp
gluetun         |          |--Regions: ukraine
gluetun         |          |--Encryption preset: strong
gluetun         |          |--Custom port: 0
gluetun         |          |--Port forwarding:
gluetun         |             |--File path: /gluetun/forwarded_port
gluetun         | |--DNS:
gluetun         |    |--Plaintext address: 1.1.1.1
gluetun         |    |--DNS over TLS:
gluetun         |       |--Unbound:
gluetun         |           |--DNS over TLS providers:
gluetun         |               |--cloudflare
gluetun         |           |--Listening port: 53
gluetun         |           |--Access control:
gluetun         |               |--Allowed:
gluetun         |                   |--0.0.0.0/0
gluetun         |                   |--::/0
gluetun         |           |--Caching: enabled
gluetun         |           |--IPv4 resolution: enabled
gluetun         |           |--IPv6 resolution: disabled
gluetun         |           |--Verbosity level: 1/5
gluetun         |           |--Verbosity details level: 0/4
gluetun         |           |--Validation log level: 0/2
gluetun         |           |--Blocked hostnames:
gluetun         |           |--Blocked IP addresses:
gluetun         |               |--127.0.0.1/8
gluetun         |               |--10.0.0.0/8
gluetun         |               |--172.16.0.0/12
gluetun         |               |--192.168.0.0/16
gluetun         |               |--169.254.0.0/16
gluetun         |               |--::1/128
gluetun         |               |--fc00::/7
gluetun         |               |--fe80::/10
gluetun         |               |--::ffff:0:0/96
gluetun         |           |--Allowed hostnames:
gluetun         |       |--Block malicious: enabled
gluetun         |       |--Update: every 24h0m0s
gluetun         | |--Firewall:
gluetun         | |--System:
gluetun         |    |--Process user ID: 1000
gluetun         |    |--Process group ID: 1000
gluetun         |    |--Timezone: america/denver
gluetun         | |--HTTP control server:
gluetun         |    |--Listening port: 8000
gluetun         |    |--Logging: enabled
gluetun         | |--Public IP getter:
gluetun         |    |--Fetch period: 12h0m0s
gluetun         |    |--IP file: /gluetun/ip
gluetun         | |--Github version information: enabled
gluetun         | 2021/05/11 20:12:46 INFO storage: merging by most recent 9140 hardcoded servers and 9140 servers read from /gluetun/servers.json
gluetun         | 2021/05/11 20:12:46 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun         | 2021/05/11 20:12:46 INFO routing: local ethernet link found: eth0
gluetun         | 2021/05/11 20:12:46 INFO routing: local ipnet found: 172.17.0.0/16
gluetun         | 2021/05/11 20:12:46 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun         | 2021/05/11 20:12:46 INFO routing: adding route for 0.0.0.0/0
gluetun         | 2021/05/11 20:12:46 INFO firewall: firewall disabled, only updating allowed subnets internal list
gluetun         | 2021/05/11 20:12:46 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun         | 2021/05/11 20:12:46 INFO openvpn configurator: checking for device /dev/net/tun
gluetun         | 2021/05/11 20:12:46 WARN TUN device is not available: open /dev/net/tun: no such file or directory
gluetun         | 2021/05/11 20:12:46 INFO openvpn configurator: creating /dev/net/tun
gluetun         | 2021/05/11 20:12:46 INFO firewall: enabling...
gluetun         | 2021/05/11 20:12:46 INFO firewall: enabled successfully
gluetun         | 2021/05/11 20:12:46 INFO dns over tls: using plaintext DNS at address 1.1.1.1
gluetun         | 2021/05/11 20:12:46 INFO firewall: setting VPN connection through firewall...
gluetun         | 2021/05/11 20:12:46 INFO http server: listening on 0.0.0.0:8000
gluetun         | 2021/05/11 20:12:46 INFO healthcheck: listening on 127.0.0.1:9999
gluetun         | 2021/05/11 20:12:46 INFO openvpn configurator: starting openvpn
gluetun         | 2021/05/11 20:12:46 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
gluetun         | 2021/05/11 20:12:46 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
gluetun         | 2021/05/11 20:12:46 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
gluetun         | 2021/05/11 20:12:46 INFO openvpn: REDACTED
gluetun         | 2021/05/11 20:12:46 INFO openvpn: -----END X509 CRL-----
gluetun         | 2021/05/11 20:12:46 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]REDACTED_VALID_IP:PORT
gluetun         | 2021/05/11 20:12:46 INFO openvpn: UDP link local: (not bound)
gluetun         | 2021/05/11 20:12:46 INFO openvpn: UDP link remote: [AF_INET]REDACTED_VALID_IP:PORT
gluetun         | 2021/05/11 20:12:47 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
gluetun         | 2021/05/11 20:12:47 INFO openvpn: [kiev404] Peer Connection Initiated with [AF_INET]REDACTED_VALID_IP:PORT
gluetun         | 2021/05/11 20:12:47 INFO openvpn: sitnl_send: rtnl: generic error (-101): Network unreachable
gluetun         | 2021/05/11 20:12:47 INFO openvpn: TUN/TAP device tun0 opened
gluetun         | 2021/05/11 20:12:47 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
gluetun         | 2021/05/11 20:12:47 INFO openvpn: /sbin/ip link set dev tun0 up
gluetun         | 2021/05/11 20:12:47 INFO openvpn: /sbin/ip addr add dev tun0 10.4.110.3/24
gluetun         | 2021/05/11 20:12:47 WARN openvpn: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
gluetun         | 2021/05/11 20:12:47 INFO openvpn: add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
gluetun         | 2021/05/11 20:12:47 ERROR openvpn: RTNETLINK answers: Permission denied
gluetun         | 2021/05/11 20:12:47 INFO openvpn: ERROR: Linux route -6 add command failed: external program exited with error status: 2
gluetun         | 2021/05/11 20:12:47 INFO openvpn: Initialization Sequence Completed
gluetun         | 2021/05/11 20:12:47 INFO VPN routing IP address: REDACTED_VALID_IP
gluetun         | 2021/05/11 20:12:47 INFO dns over tls: downloading DNS over TLS cryptographic files
gluetun         | 2021/05/11 20:12:48 INFO healthcheck: healthy!
gluetun         | 2021/05/11 20:12:52 INFO dns over tls: downloading hostnames and IP block lists
gluetun         | 2021/05/11 20:12:54 INFO dns over tls: init module 0: validator
gluetun         | 2021/05/11 20:12:54 INFO dns over tls: init module 1: iterator
gluetun         | 2021/05/11 20:12:54 INFO dns over tls: start of service (unbound 1.13.0).
gluetun         | 2021/05/11 20:12:55 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
gluetun         | 2021/05/11 20:12:57 INFO dns over tls: ready
gluetun         | 2021/05/11 20:12:58 INFO You are running 7 commits behind the most recent latest
gluetun         | 2021/05/11 20:12:58 INFO VPN gateway IP address: 10.4.110.1
gluetun         | 2021/05/11 20:12:58 INFO port forwarding: Found persistent forwarded port data for port 44968
gluetun         | 2021/05/11 20:12:58 INFO port forwarding: Forwarded port data expires in 38 days
gluetun         | 2021/05/11 20:12:58 INFO port forwarding: Port forwarded is 44968 expiring in 38 days
gluetun         | 2021/05/11 20:12:58 WARN port forwarding: loop exited
gluetun         | panic: assignment to entry in nil map
gluetun         | 
gluetun         | goroutine 150 [running]:
gluetun         | net/url.Values.Add(...)
gluetun         | 	net/url/url.go:904
gluetun         | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.bindPort(0xcb14f8, 0xc00006a380, 0xc0003fdda0, 0xc0000d8464, 0x4, 0x388, 0xafa8, 0xc00125c000, 0x7c, 0xc00006c660, ...)
gluetun         | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:419 +0x1dc
gluetun         | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*PIA).PortForward.func2(0x10, 0x10)
gluetun         | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:84 +0xd0
gluetun         | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.tryUntilSuccessful(0xcb14f8, 0xc00006a380, 0xcb2178, 0xc00054d310, 0xc000189e10)
gluetun         | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/try.go:14 +0x55
gluetun         | github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*PIA).PortForward(0xc0001f9680, 0xcb14f8, 0xc00006a380, 0xc00006e030, 0xc0000a2168, 0xcb2178, 0xc00054d310, 0xc0000d8464, 0x4, 0x388, ...)
gluetun         | 	github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:83 +0x77b
gluetun         | github.com/qdm12/gluetun/internal/openvpn.(*looper).portForward(0xc00016a000, 0xcb14f8, 0xc00006a380, 0xc00038e0b0, 0xcb0320, 0xc0001f9680, 0xc00006e030, 0xc0000d8464, 0x4, 0x388)
gluetun         | 	github.com/qdm12/gluetun/internal/openvpn/loop.go:314 +0x1e7
gluetun         | created by github.com/qdm12/gluetun/internal/openvpn.(*looper).Run.func1
gluetun         | 	github.com/qdm12/gluetun/internal/openvpn/loop.go:187 +0x105
gluetun exited with code 1
```

**Comment by qdm12** [comment]
https://github.com/qdm12/gluetun/commit/33253c0cfc7f635357ae95d548644a2ef8ca077a fixes it for `:latest`, sorry about that!

@jarulsamy however, I can't find the same bug on `v3.17.0`, would you mind trying it and post logs here? Thanks!!

**Comment by jarulsamy** [comment]
@qdm12, sorry. that's my fault. I assumed that `:latest` and `:v3.17.0` were the same version. I just tried running both v3.17.0 and latest and both are working properly. It is probably safe to close this issue thread now. Thanks for such a speedy fix!
