### ISSUE TITLE
Bug: HTTP control server returns empty reply for forwarded port

### ISSUE THREAD

**Issue by nearcatch** [qdm12/gluetun#552]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Unraid 6.9.2

```bash
cat /etc/os-release

NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current
```

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: pia

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-07-31T22:42:24Z (commit f339c88)
```

**What's the problem** 🤔

Curling the forwarded port doesn't work anymore.

The exact command I used:
```bash
QBT_VPN_GLUETUN_ADDR=http://gluetun:8000
QBT_VPN_PORT=$(curl -s -f ${QBT_VPN_GLUETUN_ADDR}/v1/openvpn/portforwarded | jq '.port' | jq -r 'select(.!=null)')
```
Normally this results in `QBT_VPN_PORT` being set to the forwarded port.

When it stopped working I tried without the silent switches and received the following:

```bash
root@unraid: curl http://gluetun:8000/v1/openvpn/portforwarded
curl: (52) Empty reply from server
```

**Share your logs... (careful to remove in example tokens)**

```log
2021-08-01 00:55:01.73228039 CDT ========================================
2021-08-01 00:55:01.73230548 CDT ========================================
2021-08-01 00:55:01.73231499 CDT =============== gluetun ================
2021-08-01 00:55:01.73231849 CDT ========================================
2021-08-01 00:55:01.73232162 CDT =========== Made with ❤️ by ============
2021-08-01 00:55:01.73232528 CDT ======= https://github.com/qdm12 =======
2021-08-01 00:55:01.73232851 CDT ========================================
2021-08-01 00:55:01.73233178 CDT ========================================
2021-08-01 00:55:01.73233498 CDT
2021-08-01 00:55:01.73233800 CDT Running version latest built on 2021-07-31T22:42:24Z (commit f339c88)
2021-08-01 00:55:01.73234201 CDT
2021-08-01 00:55:01.73234498 CDT 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
2021-08-01 00:55:01.73234826 CDT 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
2021-08-01 00:55:01.73235146 CDT ✨ New feature? https://github.com/qdm12/gluetun/issues/new
2021-08-01 00:55:01.73235473 CDT ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
2021-08-01 00:55:01.73235804 CDT 💻 Email? quentin.mcgaw@gmail.com
2021-08-01 00:55:01.73236118 CDT 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2021-08-01 00:55:01.73259486 CDT 2021/08/01 00:55:01 INFO Alpine version: 3.14.0
2021-08-01 00:55:01.73908053 CDT 2021/08/01 00:55:01 INFO OpenVPN 2.4 version: 2.4.11
2021-08-01 00:55:01.74175441 CDT 2021/08/01 00:55:01 INFO OpenVPN 2.5 version: 2.5.2
2021-08-01 00:55:01.74462877 CDT 2021/08/01 00:55:01 INFO Unbound version: 1.13.1
2021-08-01 00:55:01.76107156 CDT 2021/08/01 00:55:01 INFO IPtables version: v1.8.7
2021-08-01 00:55:01.76275613 CDT 2021/08/01 00:55:01 INFO Settings summary below:
2021-08-01 00:55:01.76277129 CDT |--OpenVPN:
2021-08-01 00:55:01.76277629 CDT    |--Version: 2.5
2021-08-01 00:55:01.76278048 CDT    |--Verbosity level: 1
2021-08-01 00:55:01.76278539 CDT    |--Run as root: enabled
2021-08-01 00:55:01.76279103 CDT    |--Provider:
2021-08-01 00:55:01.76279659 CDT       |--Private Internet Access settings:
2021-08-01 00:55:01.76280267 CDT          |--Network protocol: udp
2021-08-01 00:55:01.76281531 CDT          |--Regions: ca montreal
2021-08-01 00:55:01.76282080 CDT          |--Encryption preset: strong
2021-08-01 00:55:01.76282639 CDT          |--Port forwarding:
2021-08-01 00:55:01.76283191 CDT             |--File path: /gluetun/forwarded_port
2021-08-01 00:55:01.76283796 CDT |--DNS:
2021-08-01 00:55:01.76284426 CDT    |--Plaintext address: 1.1.1.1
2021-08-01 00:55:01.76285012 CDT    |--DNS over TLS:
2021-08-01 00:55:01.76285582 CDT       |--Unbound:
2021-08-01 00:55:01.76287667 CDT           |--DNS over TLS providers:
2021-08-01 00:55:01.76288453 CDT               |--Cloudflare
2021-08-01 00:55:01.76289094 CDT           |--Listening port: 53
2021-08-01 00:55:01.76289698 CDT           |--Access control:
2021-08-01 00:55:01.76290295 CDT               |--Allowed:
2021-08-01 00:55:01.76290888 CDT                   |--0.0.0.0/0
2021-08-01 00:55:01.76291484 CDT                   |--::/0
2021-08-01 00:55:01.76292099 CDT           |--Caching: enabled
2021-08-01 00:55:01.76292684 CDT           |--IPv4 resolution: enabled
2021-08-01 00:55:01.76293278 CDT           |--IPv6 resolution: disabled
2021-08-01 00:55:01.76293834 CDT           |--Verbosity level: 1/5
2021-08-01 00:55:01.76294408 CDT           |--Verbosity details level: 0/4
2021-08-01 00:55:01.76294939 CDT           |--Validation log level: 0/2
2021-08-01 00:55:01.76295490 CDT           |--Username:
2021-08-01 00:55:01.76296074 CDT       |--Blacklist:
2021-08-01 00:55:01.76296596 CDT          |--Blocked categories:
2021-08-01 00:55:01.76297088 CDT          |--Additional IP networks blocked: 13
2021-08-01 00:55:01.76297586 CDT |--Firewall:
2021-08-01 00:55:01.76298059 CDT |--System:
2021-08-01 00:55:01.76298537 CDT    |--Process user ID: 1000
2021-08-01 00:55:01.76299018 CDT    |--Process group ID: 100
2021-08-01 00:55:01.76299489 CDT    |--Timezone: TZ
2021-08-01 00:55:01.76299953 CDT |--HTTP proxy:
2021-08-01 00:55:01.76300423 CDT    |--Port: 1080
2021-08-01 00:55:01.76300916 CDT    |--Authentication: enabled
2021-08-01 00:55:01.76301331 CDT    |--Stealth: enabled
2021-08-01 00:55:01.76301734 CDT |--Health:
2021-08-01 00:55:01.76302139 CDT    |--Server address: 127.0.0.1:9999
2021-08-01 00:55:01.76302546 CDT    |--OpenVPN:
2021-08-01 00:55:01.76302949 CDT       |--Initial duration: 6s
2021-08-01 00:55:01.76303352 CDT       |--Addition duration: 5s
2021-08-01 00:55:01.76303755 CDT |--HTTP control server:
2021-08-01 00:55:01.76304157 CDT    |--Listening port: 8000
2021-08-01 00:55:01.76304561 CDT    |--Logging: enabled
2021-08-01 00:55:01.76304963 CDT |--Updater:
2021-08-01 00:55:01.76305363 CDT    |--Period: every 24h0m0s
2021-08-01 00:55:01.76305767 CDT |--Public IP getter:
2021-08-01 00:55:01.76306169 CDT    |--Fetch period: 12h0m0s
2021-08-01 00:55:01.76306577 CDT    |--IP file: /gluetun/ip
2021-08-01 00:55:01.80204802 CDT 2021/08/01 00:55:01 INFO storage: merging by most recent 11000 hardcoded servers and 11000 servers read from /gluetun/servers.json
2021-08-01 00:55:01.85109537 CDT 2021/08/01 00:55:01 INFO routing: default route found: interface eth0, gateway 192.168.90.1
2021-08-01 00:55:01.85120250 CDT 2021/08/01 00:55:01 INFO routing: local ethernet link found: gretap0
2021-08-01 00:55:01.85121944 CDT 2021/08/01 00:55:01 INFO routing: local ethernet link found: erspan0
2021-08-01 00:55:01.85122405 CDT 2021/08/01 00:55:01 INFO routing: local ethernet link found: eth0
2021-08-01 00:55:01.85122939 CDT 2021/08/01 00:55:01 INFO routing: local ipnet found: 192.168.90.0/24
2021-08-01 00:55:01.85213459 CDT 2021/08/01 00:55:01 INFO routing: default route found: interface eth0, gateway 192.168.90.1
2021-08-01 00:55:01.85218332 CDT 2021/08/01 00:55:01 INFO routing: adding route for 0.0.0.0/0
2021-08-01 00:55:01.85221360 CDT 2021/08/01 00:55:01 INFO firewall: firewall disabled, only updating allowed subnets internal list
2021-08-01 00:55:01.85225379 CDT 2021/08/01 00:55:01 INFO routing: default route found: interface eth0, gateway 192.168.90.1
2021-08-01 00:55:01.85226075 CDT 2021/08/01 00:55:01 INFO openvpn configurator: checking for device /dev/net/tun
2021-08-01 00:55:01.85227100 CDT 2021/08/01 00:55:01 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021-08-01 00:55:01.85227693 CDT 2021/08/01 00:55:01 INFO openvpn configurator: creating /dev/net/tun
2021-08-01 00:55:01.85230730 CDT 2021/08/01 00:55:01 INFO firewall: enabling...
2021-08-01 00:55:01.86461079 CDT 2021/08/01 00:55:01 INFO firewall: enabled successfully
2021-08-01 00:55:01.86475188 CDT 2021/08/01 00:55:01 INFO http server: listening on :8000
2021-08-01 00:55:01.86476142 CDT 2021/08/01 00:55:01 INFO http proxy: listening on :1080
2021-08-01 00:55:01.86478940 CDT 2021/08/01 00:55:01 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2021-08-01 00:55:01.86485590 CDT 2021/08/01 00:55:01 INFO healthcheck: listening on 127.0.0.1:9999
2021-08-01 00:55:01.86506099 CDT 2021/08/01 00:55:01 INFO firewall: setting VPN connection through firewall...
2021-08-01 00:55:01.86616471 CDT 2021/08/01 00:55:01 INFO openvpn configurator: starting OpenVPN 2.5
2021-08-01 00:55:01.86841679 CDT 2021/08/01 00:55:01 INFO openvpn: 2021-08-01 00:55:01 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021-08-01 00:55:01.86855674 CDT 2021/08/01 00:55:01 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021-08-01 00:55:01.86856064 CDT 2021/08/01 00:55:01 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021-08-01 00:55:01.86952557 CDT 2021/08/01 00:55:01 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
2021-08-01 00:55:01.86956525 CDT 2021/08/01 00:55:01 INFO openvpn: long text string
2021-08-01 00:55:01.86957852 CDT 2021/08/01 00:55:01 INFO openvpn: -----END X509 CRL-----
2021-08-01 00:55:01.86972044 CDT 2021/08/01 00:55:01 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]199.36.223.218:1197
2021-08-01 00:55:01.86974749 CDT 2021/08/01 00:55:01 INFO openvpn: UDP link local: (not bound)
2021-08-01 00:55:01.86976179 CDT 2021/08/01 00:55:01 INFO openvpn: UDP link remote: [AF_INET]199.36.223.218:1197
2021-08-01 00:55:02.14903175 CDT 2021/08/01 00:55:02 INFO openvpn: [montreal410] Peer Connection Initiated with [AF_INET]199.36.223.218:1197
2021-08-01 00:55:02.18485367 CDT 2021/08/01 00:55:02 INFO openvpn: TUN/TAP device tun0 opened
2021-08-01 00:55:02.18488010 CDT 2021/08/01 00:55:02 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
2021-08-01 00:55:02.18789354 CDT 2021/08/01 00:55:02 INFO openvpn: /sbin/ip link set dev tun0 up
2021-08-01 00:55:02.18873947 CDT 2021/08/01 00:55:02 INFO openvpn: /sbin/ip addr add dev tun0 10.24.110.7/24
2021-08-01 00:55:02.19174380 CDT 2021/08/01 00:55:02 INFO openvpn: Initialization Sequence Completed
2021-08-01 00:55:02.19191447 CDT 2021/08/01 00:55:02 INFO VPN routing IP address: 256.256.256.256
2021-08-01 00:55:02.19192427 CDT 2021/08/01 00:55:02 INFO dns over tls: downloading DNS over TLS cryptographic files
2021-08-01 00:55:02.19196852 CDT 2021/08/01 00:55:02 INFO openvpn: VPN gateway IP address: 10.24.110.1
2021-08-01 00:55:02.19256279 CDT 2021/08/01 00:55:02 INFO port forwarding: Found saved forwarded port data for port 25730
2021-08-01 00:55:02.19258042 CDT 2021/08/01 00:55:02 INFO port forwarding: Forwarded port data expires in 54 days
2021-08-01 00:55:02.19258617 CDT 2021/08/01 00:55:02 INFO port forwarding: Port forwarded data expires in 54 days
2021-08-01 00:55:02.33491008 CDT 2021/08/01 00:55:02 INFO port forwarding: port forwarded is 25730
2021-08-01 00:55:02.33492984 CDT 2021/08/01 00:55:02 INFO firewall: setting allowed input port 25730 through interface tun0...
2021-08-01 00:55:02.33807665 CDT 2021/08/01 00:55:02 INFO port forwarding: writing port file /gluetun/forwarded_port
2021-08-01 00:55:02.81392128 CDT 2021/08/01 00:55:02 INFO dns over tls: downloading hostnames and IP block lists
2021-08-01 00:55:02.82478238 CDT 2021/08/01 00:55:02 INFO dns over tls: init module 0: validator
2021-08-01 00:55:02.82482687 CDT 2021/08/01 00:55:02 INFO dns over tls: init module 1: iterator
2021-08-01 00:55:02.86943341 CDT 2021/08/01 00:55:02 INFO dns over tls: start of service (unbound 1.13.1).
2021-08-01 00:55:03.01972654 CDT 2021/08/01 00:55:03 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021-08-01 00:55:03.02547784 CDT 2021/08/01 00:55:03 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021-08-01 00:55:03.33071465 CDT 2021/08/01 00:55:03 INFO dns over tls: ready
2021-08-01 00:55:03.33075119 CDT 2021/08/01 00:55:03 INFO healthcheck: healthy!
2021-08-01 00:55:04.12731209 CDT 2021/08/01 00:55:04 INFO ip getter: Public IP address is 256.256.256.256. ()
2021-08-01 00:55:16.58445644 CDT 2021/08/01 00:55:16 http: panic serving 192.168.90.24:51190: runtime error: invalid memory address or nil pointer dereference
2021-08-01 00:55:16.58447093 CDT goroutine 213 [running]:
2021-08-01 00:55:16.58447421 CDT net/http.(*conn).serve.func1(0xc0007c81e0)
2021-08-01 00:55:16.58448064 CDT        net/http/server.go:1804 +0x153
2021-08-01 00:55:16.58448663 CDT panic(0x8acac0, 0xea25c0)
2021-08-01 00:55:16.58449608 CDT        runtime/panic.go:971 +0x499
2021-08-01 00:55:16.58450099 CDT github.com/qdm12/gluetun/internal/server.(*openvpnHandler).getPortForwarded(0xc0006442c0, 0xc4fe30, 0xc000eac140)
2021-08-01 00:55:16.58450459 CDT        github.com/qdm12/gluetun/internal/server/openvpn.go:110 +0x3f
2021-08-01 00:55:16.58450786 CDT github.com/qdm12/gluetun/internal/server.(*openvpnHandler).ServeHTTP(0xc0006442c0, 0xc4fe30, 0xc000eac140, 0xc0007ca300)
2021-08-01 00:55:16.58451072 CDT        github.com/qdm12/gluetun/internal/server/openvpn.go:52 +0x2ae
2021-08-01 00:55:16.58451331 CDT github.com/qdm12/gluetun/internal/server.(*handlerV1).ServeHTTP(0xc000642100, 0xc4fe30, 0xc000eac140, 0xc0007ca300)
2021-08-01 00:55:16.58451610 CDT        github.com/qdm12/gluetun/internal/server/handlerv1.go:39 +0x335
2021-08-01 00:55:16.58451894 CDT github.com/qdm12/gluetun/internal/server.(*handler).ServeHTTP(0xc000632240, 0xc4fe30, 0xc000eac140, 0xc0007ca300)
2021-08-01 00:55:16.58452150 CDT        github.com/qdm12/gluetun/internal/server/handler.go:52 +0x119
2021-08-01 00:55:16.58452400 CDT github.com/qdm12/gluetun/internal/server.(*logMiddleware).ServeHTTP(0xc00063c690, 0xc500a0, 0xc0007ee000, 0xc0007ca300)
2021-08-01 00:55:16.58452668 CDT        github.com/qdm12/gluetun/internal/server/log.go:36 +0xf7
2021-08-01 00:55:16.58452920 CDT net/http.serverHandler.ServeHTTP(0xc000d7e0e0, 0xc500a0, 0xc0007ee000, 0xc0007ca300)
2021-08-01 00:55:16.58453173 CDT        net/http/server.go:2867 +0xa3
2021-08-01 00:55:16.58453422 CDT net/http.(*conn).serve(0xc0007c81e0, 0xc50f80, 0xc000c5c380)
2021-08-01 00:55:16.58453674 CDT        net/http/server.go:1932 +0x8cd
2021-08-01 00:55:16.58453923 CDT created by net/http.(*Server).Serve
2021-08-01 00:55:16.58454172 CDT        net/http/server.go:2993 +0x39b
```

**Comment by qdm12** [comment]
Hey there, thanks for reporting the bug!

Bug was introduced with 2998cf5e4854b0b451b2f0618a89e1d8bcf07e90 (no release associated). It's now fixed in `:latest`.

You can either:

- re-pull the `qmcgaw/gluetun` image once it's built [here](https://github.com/qdm12/gluetun/actions/runs/1087554019) (takes ~5-10 minutes)
- use the image `qmcgaw/gluetun:v3.21.0` which doesn't have the bug I think
