### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Smiggel** [qdm12/gluetun#667]
### Is this urgent?

Yes

### VPN service provider

NordVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Latest

### What's the problem 🤔

Running the docker version on a Raspberry Pi 4.

The docker container stops after a few tries to start the image.

### Share your logs

```log
2021/10/09 20:04:31 INFO routing: default route found: interface eth0, gateway 172.27.0.1,
2021/10/09 20:04:31 INFO routing: local ethernet link found: eth0,
2021/10/09 20:04:31 INFO routing: local ipnet found: 172.27.0.0/16,
2021/10/09 20:04:31 INFO routing: default route found: interface eth0, gateway 172.27.0.1,
2021/10/09 20:04:31 INFO routing: adding route for 0.0.0.0/0,
2021/10/09 20:04:31 INFO firewall: firewall disabled, only updating allowed subnets internal list,
2021/10/09 20:04:31 INFO routing: default route found: interface eth0, gateway 172.27.0.1,
2021/10/09 20:04:31 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...,
2021/10/09 20:04:31 INFO firewall: enabling...,
2021/10/09 20:04:31 INFO firewall: enabled successfully,
2021/10/09 20:04:31 INFO http server: listening on :8000,
2021/10/09 20:04:31 INFO healthcheck: listening on 127.0.0.1:9999,
2021/10/09 20:04:31 INFO dns over tls: using plaintext DNS at address 1.1.1.1,
2021/10/09 20:04:31 INFO firewall: setting VPN connection through firewall...,
2021/10/09 20:04:31 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021,
2021/10/09 20:04:31 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10,
2021/10/09 20:04:31 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]195.206.105.243:1194,
2021/10/09 20:04:31 INFO openvpn: UDP link local: (not bound),
2021/10/09 20:04:31 INFO openvpn: UDP link remote: [AF_INET]195.206.105.243:1194,
2021/10/09 20:04:31 INFO openvpn: VERIFY ERROR: depth=2, error=format error in certificate's notBefore field: C=PA, O=NordVPN, CN=NordVPN Root CA, serial=1,
2021/10/09 20:04:31 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
2021/10/09 20:04:31 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error,
2021/10/09 20:04:31 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error,
2021/10/09 20:04:31 INFO openvpn: TLS Error: TLS handshake failed,
2021/10/09 20:04:31 INFO openvpn: SIGTERM received, sending exit notification to peer,
2021/10/09 20:04:31 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting,
2021/10/09 20:04:31 INFO vpn: retrying in 15s,
2021/10/09 20:04:37 INFO healthcheck: program has been unhealthy for 6s: restarting VPN,
2021/10/09 20:04:46 INFO firewall: setting VPN connection through firewall...,
2021/10/09 20:04:46 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021,
2021/10/09 20:04:46 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10,
2021/10/09 20:04:46 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]31.13.191.166:1194,
2021/10/09 20:04:46 INFO openvpn: UDP link local: (not bound),
2021/10/09 20:04:46 INFO openvpn: UDP link remote: [AF_INET]31.13.191.166:1194,
2021/10/09 20:04:47 INFO openvpn: VERIFY ERROR: depth=2, error=format error in certificate's notBefore field: C=PA, O=NordVPN, CN=NordVPN Root CA, serial=1,
2021/10/09 20:04:47 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
2021/10/09 20:04:47 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error,
2021/10/09 20:04:47 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error,
2021/10/09 20:04:47 INFO openvpn: TLS Error: TLS handshake failed,
2021/10/09 20:04:47 INFO openvpn: SIGTERM received, sending exit notification to peer,
2021/10/09 20:04:47 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting,
2021/10/09 20:04:47 INFO vpn: retrying in 15s,
2021/10/09 20:04:57 INFO healthcheck: program has been unhealthy for 11s: restarting VPN,
2021/10/09 20:05:02 INFO firewall: setting VPN connection through firewall...,
2021/10/09 20:05:02 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021,
2021/10/09 20:05:02 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10,
2021/10/09 20:05:02 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]213.232.87.117:1194,
2021/10/09 20:05:02 INFO openvpn: UDP link local: (not bound),
2021/10/09 20:05:02 INFO openvpn: UDP link remote: [AF_INET]213.232.87.117:1194,
2021/10/09 20:05:02 INFO openvpn: VERIFY ERROR: depth=2, error=format error in certificate's notBefore field: C=PA, O=NordVPN, CN=NordVPN Root CA, serial=1,
2021/10/09 20:05:02 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
2021/10/09 20:05:02 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error,
2021/10/09 20:05:02 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error,
2021/10/09 20:05:02 INFO openvpn: TLS Error: TLS handshake failed,
2021/10/09 20:05:02 INFO openvpn: SIGTERM received, sending exit notification to peer,
2021/10/09 20:05:02 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting,
panic: close of closed channel,
,
goroutine 93 [running]:,
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0x296c0a0, {0x83f06c, 0x2950660}, 0x236e940),
	github.com/qdm12/gluetun/internal/vpn/run.go:98 +0x98c,
created by main._main,
	./main.go:367 +0x2718
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /srv/dev-disk-by-uuid-da2c77d4-4821-486d-856a-a7931cd0d6aa/Configs/Gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPNSP=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=<replaced email>
      - OPENVPN_PASSWORD=<replaced password>
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESS=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Europe/Amsterdam
```

**Comment by qdm12** [comment]
Same as #666 try with image tag `:666`. Please continue the conversation on #666 thanks! Note I'm away so it might take me longer to fix stuff up.
