### ISSUE TITLE
Bug: Service fails to start due to invalid argument to Intn

### ISSUE THREAD

**Issue by mtaanquist** [qdm12/gluetun#945]
### Is this urgent?

No

### Host OS

Windows 11

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-16T20:29:56.414Z (commit bddead5)

### What's the problem 🤔

Attempting to start the container with the basic example on e.g. the NordVPN wiki page fails with a panic in Go code. It works if specifically specifying the latest release version ([v3.28.2](https://github.com/qdm12/gluetun/releases/tag/v3.28.2)).

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2022-04-16T20:29:56.414Z (commit bddead5)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022-04-17T14:15:11Z INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.2
2022-04-17T14:15:11Z INFO [routing] local ethernet link found: eth0
2022-04-17T14:15:11Z INFO [routing] local ipnet found: 172.17.0.0/16
2022-04-17T14:15:11Z INFO [firewall] enabling...
2022-04-17T14:15:11Z INFO [firewall] enabled successfully
2022-04-17T14:15:11Z INFO [storage] creating /gluetun/servers.json with 11077 hardcoded servers
2022-04-17T14:15:11Z INFO Alpine version: 3.15.4
2022-04-17T14:15:11Z INFO OpenVPN 2.4 version: 2.4.12
2022-04-17T14:15:11Z INFO OpenVPN 2.5 version: 2.5.6
2022-04-17T14:15:11Z INFO Unbound version: 1.13.2
2022-04-17T14:15:11Z INFO IPtables version: v1.8.7
2022-04-17T14:15:11Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: nordvpn
|   |   └── Server selection settings:
|   |       ├── VPN type: openvpn
|   |       ├── Regions: netherlands
|   |       └── OpenVPN server selection settings:
|   |           └── Protocol: UDP
|   └── OpenVPN settings:
|       ├── OpenVPN version: 2.5
|       ├── User: [set]
|       ├── Password: [set]
|       ├── Tunnel IPv6: no
|       ├── Network interface: tun0
|       ├── Run OpenVPN as: root
|       └── Verbosity level: 1
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   └── VPN wait durations:
|       ├── Initial duration: 5s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2022-04-17T14:15:11Z INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.2
2022-04-17T14:15:11Z INFO [routing] adding route for 0.0.0.0/0
2022-04-17T14:15:11Z INFO [firewall] setting allowed subnets...
2022-04-17T14:15:11Z INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.2
2022-04-17T14:15:11Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022-04-17T14:15:11Z INFO [pprof] http server listening on [::]:6060
2022-04-17T14:15:11Z INFO [http server] http server listening on [::]:8000
2022-04-17T14:15:11Z INFO [healthcheck] listening on 127.0.0.1:9999
2022-04-17T14:15:11Z INFO [dns over tls] using plaintext DNS at address 1.1.1.1
panic: invalid argument to Intn

goroutine 106 [running]:
math/rand.(*Rand).Intn(0xc00055e430, 0xca4058)
        math/rand/rand.go:168 +0x65
github.com/qdm12/gluetun/internal/provider/utils.pickRandomConnection({0xc00057c000, 0x0, 0xc00057c000}, {0xca4058, 0xc00054e000})
        github.com/qdm12/gluetun/internal/provider/utils/pick.go:37 +0xb8
github.com/qdm12/gluetun/internal/provider/utils.PickConnection({_, _, _}, {{0xc000026029, 0x7}, {0xfd6ac8, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/qdm12/gluetun/internal/provider/utils/pick.go:27 +0x173
github.com/qdm12/gluetun/internal/provider/nordvpn.(*Nordvpn).GetConnection(_, {{0xc000026029, 0x7}, {0xfd6ac8, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc00009ef10, ...}, ...})
        github.com/qdm12/gluetun/internal/provider/nordvpn/connection.go:37 +0x1c5
github.com/qdm12/gluetun/internal/vpn.setupOpenVPN({_, _}, {_, _}, {_, _}, {_, _}, {{0xc000026029, 0x7}, ...}, ...)
        github.com/qdm12/gluetun/internal/vpn/openvpn.go:20 +0xbb
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc000441680, {0xca8af8, 0xc0004d77c0}, 0xc00046b0e0)
        github.com/qdm12/gluetun/internal/vpn/run.go:41 +0x4fa
created by main._main
        ./main.go:386 +0x2e85
```

### Share your configuration

```yml
docker run -it --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=nordvpn -e OPENVPN_USER=abc -e OPENVPN_PASSWORD=abc -e SERVER_REGIONS=Netherlands qmcgaw/gluetun
```

**Comment by qdm12** [comment]
Yes I just broke this yesterday evening indeed, thanks for taking the time to create the issue! :+1: :+1: 

I re-wrote the commit aa729515b93e1a3ab31b212559d337595e976103 to fix this.
I also added a check (0dd723b29fea11470ad6890d033c2a24a9be79d2) to prevent this panic in the future and show a more useful error message, in case no IP addresses is found in the servers filtered.
