### ISSUE TITLE
Bug:  Gluetun Container Doesn't Start After Update

### ISSUE THREAD

**Issue by ingsocdev** [qdm12/gluetun#948]
### Is this urgent?

Yes

### Host OS

Ubuntu 20.04.4 LTS

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-16T20:29:56.414Z (commit bddead5)

### What's the problem 🤔

Container does not start and keeps reporting unhealthy and restarting.

### Share your logs

```log
Running version latest built on 2022-04-16T20:29:56.414Z (commit bddead5)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022-04-17T19:56:33Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1 and assigned IP 172.19.0.5
2022-04-17T19:56:33Z INFO [routing] local ethernet link found: eth0
2022-04-17T19:56:33Z INFO [routing] local ipnet found: 172.19.0.0/16
2022-04-17T19:56:33Z INFO [firewall] enabling...
2022-04-17T19:56:33Z INFO [firewall] enabled successfully
2022-04-17T19:56:34Z INFO [storage] merging by most recent 11077 hardcoded servers and 11077 servers read from /gluetun/servers.json
2022-04-17T19:56:34Z INFO Alpine version: 3.15.4
2022-04-17T19:56:34Z INFO OpenVPN 2.4 version: 2.4.12
2022-04-17T19:56:34Z INFO OpenVPN 2.5 version: 2.5.6
2022-04-17T19:56:34Z INFO Unbound version: 1.13.2
2022-04-17T19:56:34Z INFO IPtables version: v1.8.7
2022-04-17T19:56:34Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: nordvpn
|   |   └── Server selection settings:
|   |       ├── VPN type: openvpn
|   |       ├── Regions: netherlands
|   |       └── OpenVPN server selection settings:
|   |           └── Protocol: UDP
|   └── OpenVPN settings:
|       ├── OpenVPN version: 2.5
|       ├── User: [set]
|       ├── Password: [set]
|       ├── Tunnel IPv6: no
|       ├── Network interface: tun0
|       ├── Run OpenVPN as: root
|       └── Verbosity level: 1
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   └── VPN wait durations:
|       ├── Initial duration: 5s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2022-04-17T19:56:34Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1 and assigned IP 172.19.0.5
2022-04-17T19:56:34Z INFO [routing] adding route for 0.0.0.0/0
2022-04-17T19:56:34Z INFO [firewall] setting allowed subnets...
2022-04-17T19:56:34Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1 and assigned IP 172.19.0.5
2022-04-17T19:56:34Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022-04-17T19:56:34Z INFO [pprof] http server listening on [::]:6060
2022-04-17T19:56:34Z INFO [http server] http server listening on [::]:8000
2022-04-17T19:56:34Z INFO [healthcheck] listening on 127.0.0.1:9999
2022-04-17T19:56:34Z INFO [dns over tls] using plaintext DNS at address 1.1.1.1
panic: invalid argument to Intn

goroutine 97 [running]:
math/rand.(*Rand).Intn(0xc000bc0430, 0xca4058)
        math/rand/rand.go:168 +0x65
github.com/qdm12/gluetun/internal/provider/utils.pickRandomConnection({0xc000bf8000, 0x0, 0xc000bf8000}, {0xca4058, 0xc00012d500})
        github.com/qdm12/gluetun/internal/provider/utils/pick.go:37 +0xb8
github.com/qdm12/gluetun/internal/provider/utils.PickConnection({_, _, _}, {{0xc00002a009, 0x7}, {0xfd6ac8, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/qdm12/gluetun/internal/provider/utils/pick.go:27 +0x173
github.com/qdm12/gluetun/internal/provider/nordvpn.(*Nordvpn).GetConnection(_, {{0xc00002a009, 0x7}, {0xfd6ac8, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000074340, ...}, ...})
        github.com/qdm12/gluetun/internal/provider/nordvpn/connection.go:37 +0x1c5
github.com/qdm12/gluetun/internal/vpn.setupOpenVPN({_, _}, {_, _}, {_, _}, {_, _}, {{0xc00002a009, 0x7}, ...}, ...)
        github.com/qdm12/gluetun/internal/vpn/openvpn.go:20 +0xbb
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc00046c640, {0xca8af8, 0xc0004d1600}, 0xc00048f080)
        github.com/qdm12/gluetun/internal/vpn/run.go:41 +0x4fa
created by main._main
        ./main.go:386 +0x2e85
```

**Comment by qdm12** [comment]
I fixed it today (see #945), try pulling the latest image again :wink:
